algoritmo "semnome"
// Função :
// Autor :
// Data : 17/04/2026
// Seção de Declarações 
var
nome : caracter
res , a , b , c : real

inicio
escreval  ("Digite o seu nome")
leia (nome)

escreval  ("Digite a nota do primeiro bimestre")
leia (a)

escreval ("Digite a nota do segundo bimestre")
leia (b)
escreval  ("Digite a nota do terceiro bimestre")
leia (c)

res <- (a + b + c)/3

escreval ("O aluno  " ,  nome  , "  teve como média a nota  " ,  res)
// Seção de Comandos
Fimalgoritmo
