algoritmo "semnome"
// Função :
// Autor :
// Data : 17/04/2026
// Seção de Declarações 
var
valor , valor2 , c : inteiro

inicio
valor <- randi (100)

enquanto valor <> valor2 faca
escreval ("Tente adivinhar o número secreto entre 0 e 100")
leia (valor2)

se valor2 > valor entao
escreval ("O número é menor do que o digitado")

senao
se valor2 < valor entao
escreval ("O número é maior do que o digitado")

senao
escreval ("Parabéns! Você acertou!")

fimse
fimse

c <- c + 1

fimenquanto
// Seção de Comandos
fimalgoritmo
