algoritmo "semnome"
// Função :
// Autor :
// Data : 17/04/2026
// Seção de Declarações 
var
idade : inteiro
sexo : caracter

inicio
escreval ("Informe a sua idade")
leia (idade)
escreval ("Digite M para masculino")
escreval ("Digite F para masculino")
escreval ("Digite X prefiro não informar")
leia (sexo)

se (idade >= 22) e (sexo = "F") entao
escreval ("Você poderia participar da nossa pesquisa?")
senao
escreval ("Obrigado e até mais!")

fimse
// Seção de Comandos 
fimalgoritmo
