algoritmo "semnome"
// Função :
// Autor :
// Data : 17/04/2026
// Seção de Declarações 
var
idade : inteiro

inicio
escreval ("**** Escolinha de Futebol ****")
escreval ("Informe a sua idade")
leia (idade)

se idade <= 10 entao
escreval ("Aluno não atendido")

senao
se (idade >= 11) e (idade <= 13) entao
escreval ("Categoria: Adolescente")

senao
escreval ("Categoria: Adulto")

fimse
fimse
// Seção de Comandos 
fimalgoritmo
