algoritmo "semnome"
// Função :
// Autor :
// Data : 11/03/2026
// Seção de Declarações

var
a , b : inteiro
c : real

inicio
escreval  ("Digite o valor de a")
leia (a)

escreval  ("Digite o valor de b")
leia (b)

c  <-  a  +  b
escreval ("Digite o valor de à  " , c)

c  <-  a  *  b
escreval ("Digite o valor de à  " , c)

c  <-  a  /  b
escreval ("Digite o valor de à  " , c)

c  <-  a  -  b
escreval ("Digite o valor de à  " , c)
// Seção de Comandos
Fimalgoritmo
